name: Update API
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  update-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: bahmutov/npm-install@v1
    - run: npm run update-api 
      env:
        TOKEN: ${{ secrets.TOKEN }}
    - name: "Commit changes"
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add json/
        git commit -m "Scheduled Update"
        git push
